### ISSUE TITLE
tools/quick-run.sh train go az 300 -n go_9x9_az_n200 -conf_str env_board_size=9:actor_num_simulation=200   Error

### ISSUE THREAD

**Issue by yanzhenqiang** [rlglab/minizero#4]
`(Version: 4d8301)
[2024/07/11_10:03:20.280] [Version] 4d8301
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 11) > this->size() (which is 0)
scripts/zero-server.sh: line 133:  1518 Aborted                 (core dumped) ${sp_executable_file} -conf_file ${train_dir}/${new_configure_file} -conf_str ${conf_str} -mode zero_server
Terminated
User defined signal 1`

**Comment by moporgic** [comment]
Hi, thanks for your report.

It seems that this issue is caused by a minor bug in the startup script.
Please remove the existing training folder `go_9x9_az_n200` and try again.
There should be no problems this time.

**Comment by yanzhenqiang** [comment]
![image](https://github.com/rlglab/minizero/assets/5805019/b92b34c6-4893-4796-a8da-7f298b699ae5)

**Comment by yanzhenqiang** [comment]
Thanks ， I remove the dir, and then  
```shell
[2024/07/11_16:56:30.894] [Worker Disconnection] 3090_0 op
+ echo 'msg: train weight_iter_0.pkl 1 1'
msg: train weight_iter_0.pkl 1 1
+ closeFd 10
+ local fd=10
+ eval 'exec {fd}<&-'
++ exec
+ eval 'exec {fd}>&-'
++ exec
+ echo 'disconnected from broker'
disconnected from broker
+ sleep 10
Training failed to complete
```
But I cannot find the handler "train "

**Comment by moporgic** [comment]
The log `[Worker Disconnection] 3090_0 op` indicates the Python optimizer crashed, which is the cause.
Can you share the `op.log` generated inside the training folder?

**Comment by yanzhenqiang** [comment]
Thanks for your reply. I found the problem. Sorry, it was caused by my incorrect operation.
